### ISSUE TITLE
Format of log..

### ISSUE THREAD

**Issue by mydiscogr** [ishegatron/Sentinel#1]
Hi, first of all thanks to continue a good log viewer like sentinel :) 
second:
I'd like to write a logger and send message (logs) to sentinel, well, but I dunno where find format of this message, can You help me?

thanks

**Comment by ishegatron** [comment]
Thanks for your interest in Sentinel!
If I understand your question, you are trying to write a custom logger and format the incoming messages so that they display correctly in Sentinel?

My first answer is to suggest that you not write a custom logger and use NLog instead.  This is a great logging framework that allows you to create custom "targets" (one of which can be Sentinel, listening on a UDP channel) and also create custom message formats.  Check it out if you haven't already: [NLog site](http://nlog-project.org/)

If you really must write a custom logger, I imagine you would pick a message format that makes sense to you and then add a new Log Provider project to Sentinel that is specific to your logger.  Look at the Sentinel.NLog and Sentinel.Log4Net projects in the Sentinel source code as examples of how to make Sentinel understand your custom logger's format.  There is a class called NLogViewerProvider, for example, that shows how incoming packets are UTF8 decoded and then deserialized into LogEntry objects, which get displayed visually.

Hope this helps! :)

**Comment by mydiscogr** [comment]
Thanks, No I'm not need to write logger from scratch, I just want to extend https://www.nuget.org/packages/SharpLog/1.2.8, because I'd like to use it in Unity3d and Windows phone 8.1, as you know NLog not support windows 8.1 platform and is not a portable lib...

by the way I'm going to look inside your source, thanks for your answer :)

Bye
